SET C51INC=D:\Keil_v5\C51\Inc;D:\Keil_v5\C51\Inc\Atmel
SET C51LIB=D:\Keil_v5\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00A8C000
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\led.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\seg.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\beeper.__i"
"D:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\keys.__i"
"D:\Keil_v5\C51\BIN\LIB51.EXE" @".\Objects\blinky.__b"
